@startuml
'https://plantuml.com/class-diagram


interface Command {
    - receiver
    + execute()
}

interface Invoker {
    + setCommand(command)
    + executeCommand()
}

interface Container {
    - content
}

interface Receiver {
    + copy()
    + paste()
    + writing()
    + replace()
}

class TerminalGUI {
    + update()
}

class Engine {
    + copy()
    + paste()
    + writing()
    + replace()
}

class Writing {
    - receiver
    + execute()
}

class Copy {
    - receiver
    + execute()
}

class Paste {
    - receiver
    + execute()
}

class Replace {
    - receiver
    + execute()
}

class Clipboard {}

class Buffer {}

class command #line.dotted

command ..> Invoker : Invoker
command ..> Receiver : Receiver
command ..> Command : command

Receiver "1"-"0...*" Command
Receiver "*"-down-"1" Container
Receiver "*"--down"1" Container

Clipboard -up-|> Container
Buffer -left|> Container


Engine -|> Receiver

Invoker "1"--left"*" Command

Writing -up-|> Command
Copy --up-|> Command
Paste -up-|> Command
Replace --up-|> Command

TerminalGUI --|> Invoker

@enduml