@startuml
'https://plantuml.com/class-diagram

interface GUI {
    + update()
}

interface Invoker {
    + setCommand(command)
    + executeCommand()
}

interface Command {
    - receiver
    + execute()
}

interface Receiver {
    + copy(debut, fin)
    + paste(position)
    + insert(char, position)
    + delete(debut, fin)
}

interface Clipboard {
    - content
    + setContent(string)
    + getContent()
}

interface Buffer {
    - content
    + addContent(string, position)
    + deleteContent(debut, fin)
    + getContent()
    + getContent(position)
}

class SimpleGUI {
    + update()
}

class Engine {
    + copy(debut, fin)
    + paste(position)
    + insert(char, position)
    + delete(debut, fin)
}


class Copy {
    - receiver
    + execute()
}

class Cut {
    - receiver
    + execute()
}

class Paste {
    - receiver
    + execute()
}

class Replace {
    - receiver
    + execute()
}

class Delete {
    - receiver
    + execute()
}

class Insert {
    - receiver
    + execute()
}

class SimpleBuffer {
    - content
    + addContent(string, position)
    + deleteContent(debut, fin)
    + getContent()
    + getContent(position)
}

class SimpleClipboard {
    - content
    + setContent(string)
    + getContent()
}

class DummyInvoker {
    + setCommand(command)
    + executeCommand()
}


GUI --- Buffer
GUI --"0...*" Invoker

Receiver "1"-"0...*" Command
Receiver "*"-down-"1" Buffer
Receiver "*"--down"1" Clipboard

SimpleGUI -right|> GUI

Engine -right-|> Receiver

Invoker "1"--left"*" Command


Copy -up-|> Command
Paste -up-|> Command
Replace --up-|> Command
Delete -up-|> Command
Cut --up-|> Command
Insert -up--|> Command

SimpleBuffer -up-|> Buffer
SimpleClipboard -up-|> Clipboard

DummyInvoker -left|> Invoker


@enduml