@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User

participant GUI
activate GUI
participant Invoker
activate Invoker
participant Cut
participant Receiver
activate Receiver
participant Buffer
activate Buffer
participant Clipboard
activate Clipboard

User -> GUI : sélectionne borne début
User -> GUI : séléction borne fin
User -> GUI : appui sur le bouton "cut"

activate Cut

GUI -> Invoker : setCommand(new Cut(debut, fin))
GUI -> Invoker : executeCommand()

Invoker -> Cut : execute()

Cut -> Receiver : copy(debut, fin)
Receiver -> Buffer : get(debut, fin)
Buffer --> Receiver : return texte
Receiver -> Clipboard : set(texte)

Cut -> Receiver : delete(debut, fin)
Receiver -> Buffer : delete(debut, fin)

GUI -> Buffer : getContent()



@enduml