@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User

activate GUI
activate Invoker
participant Command
activate Receiver
activate Buffer

User -> GUI : texte
activate Command
GUI -> Invoker : setCommand(command)
GUI -> Invoker : executeCommand(command)
Invoker -> Command : execute()
Command -> Receiver : get()
Receiver -> Buffer : get()

Buffer --> Receiver : texte
Receiver --> Command : texte
Command --> Invoker : texte
Invoker --> GUI : texte
GUI -> User : update()

@enduml