@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User

activate GUI
activate Invoker
participant Command
activate Receiver
activate Buffer

User -> GUI : texte
activate Command
GUI -> Invoker : setCommand(command)
GUI -> Invoker : executeCommand(command)
Invoker -> Command : execute()
Command -> Receiver : insert()
Receiver -> Buffer : push_back()

GUI -> User : update()

@enduml