@startuml
'https://plantuml.com/class-diagram
'42D65B
'09B327
interface GUI #ffb480 {
    + update()
}

interface Invoker #ffb480 {
    + setCommand(Command c)
    + executeCommand()
}

interface Command #ffb480 {
    - receiver
    + execute()
}

interface Receiver #ffb480 {
    + copy(int start, int stop)
    + insert(String c, int position);
    + insertClipboard(int position)
    + delete(int start, int stop)
}

interface Clipboard #ffb480 {
    - content
    + setContent(string)
    + getContent()
}

interface Buffer #ffb480 {
    - String content
    + addContent(String s, int position)
    + deleteContent(int start, int stop)
    + getContent()
}

interface Originator #59adf6 {
    + String curentState;
    + void save();
    + void restore();
}

interface Memento #59adf6 {
    - String content

    + Memento(String s, int pos)
    + String getContent()
}

interface CareTaker #59adf6 {
    + void addMemento(Memento)
    + Memento getMemento()
    + List<Memento> getList()
}

class SimpleGUI #ff6961;line.bold:C80900 {
    + getInstance()
    + update()
}

class Engine #ff6961 {
      + copy(int start, int stop)
      + insert(String c, int position);
      + insertClipboard(int position)
      + delete(int start, int stop)
}


class Copy #ff6961 {
    - int start
    - int stop
    - receiver
    + execute()
}

class Cut #ff6961 {
    - int start
    - int stop
    - receiver
    + execute()
}

class Paste #ff6961 {
    - int position
    - receiver
    + execute()
}

class Replace #ff6961 {
    - int start
    - int stop
    - receiver
    + execute()
}

class Delete #ff6961 {
    - int position
    - receiver
    + execute()
}

class Insert #ff6961 {
    + int position
    - String insert
    - receiver
    + execute()
}

class Undo #ff6961 {
    - receiver
    + execute()
}

class Redo #ff6961 {
    - receiver
    + execute()
}

class Script #ff6961;line.bold:C80900 {
    - receiver
    + execute()
}

class Load #ff6961 {
    - receiver
    + execute()
}

class SimpleBuffer #ff6961;line.bold:C80900 {
    - String content
    + getInstance()
    + addContent(String s, int position)
    + deleteContent(int start, int stop)
    + getContent()
}

class SimpleClipboard #ff6961;line.bold:C80900 {
    - content
    + getInstance()
    + setContent(String s)
    + getContent()
}

class DummyInvoker #ff6961 {
    + setCommand(Command c)
    + executeCommand()
}

class MyOriginator #176EBB {
    + String curentState;
    + void save();
    + void restore();
}

class Snapshot #176EBB {
    - String content

    + Memento(String s, int pos)
    + String getContent()
}

class ListCareTaker #1677CB;line.bold:002D55 {
    + void addMemento(Memento)
    + Memento getMemento()
    + List<Memento> getList()
}

GUI --- "1"Buffer
GUI --"1" Invoker

Receiver "1"- Command
Receiver -down-"1" Buffer
Receiver --down"1" Clipboard

SimpleGUI -right|> GUI

Engine -right-|> Receiver

Invoker "1"--left Command

Copy -- Originator
Paste -- Originator
Replace -- Originator
Delete -- Originator
Cut -- Originator
Insert -- Originator
Undo -- Originator
Redo -- Originator
Script -- Originator
Load -- Originator

CareTaker -up- Originator
Memento -- CareTaker

Copy -up-|> Command
Paste -up-|> Command
Replace --up-|> Command
Delete -up-|> Command
Cut --up-|> Command
Insert -up--|> Command
Undo -up--|> Command
Redo -up--|> Command
Script -up-|> Command
Load -up--|> Command

SimpleBuffer -up-|> Buffer
SimpleClipboard -up-|> Clipboard

DummyInvoker -left|> Invoker

MyOriginator -left|> Originator
ListCareTaker -|> CareTaker
Snapshot -down|> Memento
@enduml
