@startuml
'https://plantuml.com/use-case-diagram

left to right direction
skinparam packageStyle rect
skinparam shadowing false

actor User
actor "Fichier" as sys

rectangle "text editor" {
    usecase "Entrer du texte" as txt
    usecase "Supprimer du texte" as select
    usecase "Copier la séléction" as cp
    usecase "Coller la selection" as paste
    usecase "Remplacer du texte" as replace
    usecase "Enregistrer des actions" as rec
    usecase "Rejouer des actions" as load

    usecase "Enregstrer des contenus" as recF
    usecase "Lire des contenus" as loadF

  User --> txt
  User --> select
  User -> cp
  User -> replace
  User -> paste
  User -> rec
  User -> load

  sys -left-> recF
  sys -up-> loadF

  (recF) <.up. (rec) : includes
  (loadF) <.up. (load) : includes
}



@enduml